export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  teableApiKey: process.env.TEABLE_API_KEY ?? "",
  teableApiUrl: process.env.TEABLE_API_URL ?? "https://app.teable.ai/api",
  teableTableId: process.env.TEABLE_TABLE_ID ?? "",
  teableGithubTableId: process.env.TEABLE_GITHUB_TABLE_ID ?? "",
  teableWeeklyViralGithubTableId: process.env.TEABLE_WEEKLY_VIRAL_GITHUB_TABLE_ID ?? "",
  teableLlmTableId: process.env.TEABLE_LLM_TABLE_ID ?? "",
  teableLtdTableId: process.env.TEABLE_LTD_TABLE_ID ?? "",
  teableVideoImageTableId: process.env.TEABLE_VIDEO_IMAGE_TABLE_ID ?? "",
  teableMusicVoiceTableId: process.env.TEABLE_MUSIC_VOICE_TABLE_ID ?? "",
  teableChatbotsTableId: process.env.TEABLE_CHATBOTS_TABLE_ID ?? "",
  teableFreeApisTableId: process.env.TEABLE_FREE_APIS_TABLE_ID ?? "",
  teableFreeLlmIdeTableId: process.env.TEABLE_FREE_LLM_IDE_TABLE_ID ?? "",
  teableVibeCodingTableId: process.env.TEABLE_VIBE_CODING_TABLE_ID ?? "",
  teableDesignerToolsTableId: process.env.TEABLE_DESIGNER_TOOLS_TABLE_ID ?? "",
  teableAiInfraTableId: process.env.TEABLE_AI_INFRA_TABLE_ID ?? "",
  teableHardwareTableId: process.env.TEABLE_HARDWARE_TABLE_ID ?? "",
  teableTestingToolsTableId: process.env.TEABLE_TESTING_TOOLS_TABLE_ID ?? "",
  teableAiSecurityTableId: process.env.TEABLE_AI_SECURITY_TABLE_ID ?? "",
  teableBusinessProductivityTableId: process.env.TEABLE_BUSINESS_PRODUCTIVITY_TABLE_ID ?? "",
  teableMcpProvidersTableId: process.env.TEABLE_MCP_PROVIDERS_TABLE_ID ?? "",
  teableVpsCloudTableId: process.env.TEABLE_VPS_CLOUD_TABLE_ID ?? "",
  teableAiMediaTableId: process.env.TEABLE_AI_MEDIA_TABLE_ID ?? "",
  teableAiInfluencersTableId: process.env.TEABLE_AI_INFLUENCERS_TABLE_ID ?? "",
  teableAiSitesTableId: process.env.TEABLE_AI_SITES_TABLE_ID ?? "",
  teableAiDiscordTableId: process.env.TEABLE_AI_DISCORD_TABLE_ID ?? "",
  teableAuSeoToolsTableId: process.env.TEABLE_AU_SEO_TOOLS_TABLE_ID ?? "",
  teableSumateTopRecommendationsTableId: process.env.TEABLE_SUMATE_TOP_RECOMMENDATIONS_TABLE_ID ?? "",
  // Table IDs are not secrets (the API key is what grants access), so this one
  // carries its real default: the front-page "This Week's AI Picks" strip then
  // works on any deploy without needing a new dashboard env var set first.
  // Still overridable by the env var if the base ever changes.
  teableThisWeeksAiPicksTableId:
    process.env.TEABLE_THIS_WEEKS_AI_PICKS_TABLE_ID ?? "tbloOK3GBpzHHUyVZeW",
};
